#

all: Release Debug ReleaseMPI DebugMPI

SRC_DIR= .

include $(SRC_DIR)/Makefile_compiler


SRCS = MiscUtils.f90 MpiUtils.f90 StringUtils.f90 ArrayUtils.f90 FileUtils.f90 \
	   IniObjects.f90 RandUtils.f90 ObjectLists.f90 MatrixUtils.f90 RangeUtils.f90 \
	   Interpolation.f90

OBJS = $(patsubst %.f90,%.o,$(SRCS))

Release:
	$(MAKE) OUTPUT_DIR=Release F90FLAGS="$(F90RELEASEFLAGS)" directories

Releaselib:
	$(MAKE) OUTPUT_DIR=Releaselib directories

ReleaseMPI:
	$(MAKE) OUTPUT_DIR=ReleaseMPI F90C=$(MPIF90C) F90FLAGS="$(F90RELEASEFLAGS) -DMPI" directories

Debug:
	$(MAKE) OUTPUT_DIR=Debug F90FLAGS="$(F90DEBUGFLAGS)" directories

Debuglib:
	$(MAKE) OUTPUT_DIR=Debuglib directories

DebugMPI:
	$(MAKE) OUTPUT_DIR=DebugMPI F90C=$(MPIF90C) F90FLAGS="$(F90DEBUGFLAGS) -DMPI" directories

%.o: $(SRC_DIR)/%.f90
	$(F90C) $(F90COMMONFLAGS) $(F90FLAGS) -o $*.o -c $<

libforutils.a: $(OBJS)
	$(AREXE) -r libforutils.a $(OBJS)

clean:
	-rm -fr Debug* Release*

# export all variables to the sub-make below
export

# Build in output dir to get file dependencies correctly and make use
# of delta builds, where only changed files and their dependents are
# rebuild.
directories:
	mkdir -p $(OUTPUT_DIR)
	$(MAKE) -C $(OUTPUT_DIR) -f../Makefile SRC_DIR=.. libforutils.a

# Include dependency files generated by a previous run of make
-include $(SRCS:.f90=.d)

.PHONY: directories clean Release Debug ReleaseMPI DebugMPI

#Avoid problems with intel gen-dep
mpif.h:
	echo ''
 
