name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Show gfortran version
      run: gfortran --version
    
    - name: Make test script executable
      run: chmod +x tests/run_tests.sh
    
    - name: Run tests
      run: ./tests/run_tests.sh
      working-directory: .
